name: web-self-service-app - Snapshot Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - '/**/*'
      - '.github/workflows/*.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - '/**'
      - 'Dockerfile'
  repository_dispatch:
    types: [build-package]

jobs:
  build-and-push:
    name: Build image and push to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # - name: Get npm dependencies
      #   run: npm install
      # - name: Build with gulp
      #   run: gulp build
      - name: Build Docker image and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: 'instateteam/web-self-service-app/ng1-web-ui-proxied-api'
          tag_with_ref: true